# Generated by Django 6.0 on 2026-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
